[2024-03-08T12:17:26.564+0530] {processor.py:161} INFO - Started process (PID=11303) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:17:26.565+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:17:26.565+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:17:26.565+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:17:26.597+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:17:26.597+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:17:26.597+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:17:26.597+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:17:26.597+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:17:26.620+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2024-03-08T12:19:19.043+0530] {processor.py:161} INFO - Started process (PID=11384) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:19:19.044+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:19:19.044+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:19:19.044+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:19:19.077+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:19:19.077+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:19:19.077+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:19:19.077+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:19:19.077+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:19:19.104+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2024-03-08T12:21:10.890+0530] {processor.py:161} INFO - Started process (PID=11460) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:21:10.890+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:21:10.890+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:21:10.890+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:21:10.922+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:21:10.922+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:21:10.922+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:21:10.922+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:21:10.923+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:21:10.946+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2024-03-08T12:22:55.282+0530] {processor.py:161} INFO - Started process (PID=11553) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:22:55.283+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:22:55.283+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:22:55.283+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:22:55.317+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:22:55.316+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:22:55.317+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:22:55.317+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:22:55.317+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:22:55.341+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2024-03-08T12:24:50.575+0530] {processor.py:161} INFO - Started process (PID=11655) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:24:50.576+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:24:50.576+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:24:50.576+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:24:50.608+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:24:50.608+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:24:50.608+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:24:50.608+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:24:50.609+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:24:50.632+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T12:26:43.672+0530] {processor.py:161} INFO - Started process (PID=11743) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:26:43.674+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:26:43.674+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:26:43.674+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:26:43.707+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:26:43.706+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:26:43.707+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:26:43.707+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:26:43.707+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:26:43.731+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2024-03-08T12:28:31.735+0530] {processor.py:161} INFO - Started process (PID=11814) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:28:31.736+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:28:31.737+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:28:31.737+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:28:31.769+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:28:31.769+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:28:31.770+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:28:31.770+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:28:31.770+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:28:31.793+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T12:30:23.264+0530] {processor.py:161} INFO - Started process (PID=11894) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:30:23.265+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:30:23.265+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:30:23.265+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:30:23.297+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:30:23.297+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:30:23.297+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:30:23.297+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:30:23.298+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:30:23.321+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T12:32:14.229+0530] {processor.py:161} INFO - Started process (PID=11966) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:32:14.230+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:32:14.230+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:32:14.230+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:32:14.264+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:32:14.263+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:32:14.264+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:32:14.264+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:32:14.264+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:32:14.287+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2024-03-08T12:34:08.365+0530] {processor.py:161} INFO - Started process (PID=12044) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:34:08.366+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:34:08.367+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:34:08.367+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:34:08.399+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:34:08.399+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:34:08.399+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:34:08.399+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:34:08.399+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:34:08.423+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T12:36:05.244+0530] {processor.py:161} INFO - Started process (PID=12117) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:36:05.244+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:36:05.244+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:36:05.244+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:36:05.276+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:36:05.276+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:36:05.276+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:36:05.276+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:36:05.276+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:36:05.300+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2024-03-08T12:37:43.109+0530] {processor.py:161} INFO - Started process (PID=12184) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:37:43.109+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:37:43.109+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:37:43.109+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:37:43.142+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:37:43.141+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:37:43.142+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:37:43.142+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:37:43.142+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:37:43.166+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2024-03-08T12:39:38.470+0530] {processor.py:161} INFO - Started process (PID=12264) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:39:38.471+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:39:38.471+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:39:38.471+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:39:38.504+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:39:38.504+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:39:38.504+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:39:38.504+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:39:38.505+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:39:38.528+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T12:41:30.640+0530] {processor.py:161} INFO - Started process (PID=12337) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:41:30.640+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:41:30.640+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:41:30.640+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:41:30.672+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:41:30.672+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:41:30.672+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:41:30.672+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:41:30.672+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:41:30.696+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2024-03-08T12:43:27.165+0530] {processor.py:161} INFO - Started process (PID=12405) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:43:27.167+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:43:27.167+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:43:27.167+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:43:27.199+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:43:27.199+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:43:27.199+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:43:27.199+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:43:27.199+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:43:27.223+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T12:45:18.027+0530] {processor.py:161} INFO - Started process (PID=12511) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:45:18.028+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:45:18.028+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:45:18.028+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:45:18.062+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:45:18.062+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:45:18.062+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:45:18.062+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:45:18.062+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:45:18.086+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2024-03-08T12:47:04.623+0530] {processor.py:161} INFO - Started process (PID=12580) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:47:04.624+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:47:04.624+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:47:04.624+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:47:04.658+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:47:04.658+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:47:04.658+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:47:04.658+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:47:04.658+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:47:04.683+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2024-03-08T12:48:59.637+0530] {processor.py:161} INFO - Started process (PID=12658) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:48:59.638+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:48:59.638+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:48:59.638+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:48:59.671+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:48:59.671+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:48:59.671+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:48:59.671+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:48:59.671+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:48:59.695+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T12:50:51.486+0530] {processor.py:161} INFO - Started process (PID=12729) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:50:51.488+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:50:51.488+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:50:51.488+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:50:51.520+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:50:51.520+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:50:51.520+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:50:51.520+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:50:51.520+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:50:51.544+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T12:52:40.251+0530] {processor.py:161} INFO - Started process (PID=12823) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:52:40.252+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:52:40.252+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:52:40.252+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:52:40.285+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:52:40.284+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:52:40.285+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:52:40.285+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:52:40.285+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:52:40.308+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T12:59:30.498+0530] {processor.py:161} INFO - Started process (PID=13135) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:59:30.499+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T12:59:30.499+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:59:30.499+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:59:30.532+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:59:30.532+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T12:59:30.532+0530] {logging_mixin.py:188} INFO - [2024-03-08T12:59:30.532+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T12:59:30.532+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T12:59:30.556+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T13:02:32.088+0530] {processor.py:161} INFO - Started process (PID=13360) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:02:32.088+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T13:02:32.089+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:02:32.089+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:02:32.123+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:02:32.123+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T13:02:32.123+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:02:32.123+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T13:02:32.124+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:02:32.147+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2024-03-08T13:04:24.876+0530] {processor.py:161} INFO - Started process (PID=13449) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:04:24.877+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T13:04:24.877+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:04:24.877+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:04:24.909+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:04:24.909+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T13:04:24.909+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:04:24.909+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T13:04:24.909+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:04:24.933+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T13:06:25.087+0530] {processor.py:161} INFO - Started process (PID=13534) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:06:25.088+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T13:06:25.089+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:06:25.089+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:06:25.121+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:06:25.120+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T13:06:25.121+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:06:25.121+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T13:06:25.121+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:06:25.145+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T13:15:09.265+0530] {processor.py:161} INFO - Started process (PID=14259) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:15:09.266+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T13:15:09.267+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:15:09.267+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:15:09.299+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:15:09.299+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T13:15:09.299+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:15:09.299+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T13:15:09.299+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:15:09.323+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T13:16:58.198+0530] {processor.py:161} INFO - Started process (PID=14363) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:16:58.199+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T13:16:58.199+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:16:58.199+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:16:58.234+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:16:58.234+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T13:16:58.235+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:16:58.235+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T13:16:58.235+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:16:58.258+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2024-03-08T13:18:44.724+0530] {processor.py:161} INFO - Started process (PID=14449) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:18:44.725+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T13:18:44.726+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:18:44.726+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:18:44.762+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:18:44.761+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T13:18:44.762+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:18:44.762+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T13:18:44.762+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:18:44.787+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2024-03-08T13:20:39.046+0530] {processor.py:161} INFO - Started process (PID=14518) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:20:39.046+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T13:20:39.047+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:20:39.047+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:20:39.079+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:20:39.079+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T13:20:39.079+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:20:39.079+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T13:20:39.080+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:20:39.103+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2024-03-08T13:23:01.918+0530] {processor.py:161} INFO - Started process (PID=14720) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:23:01.919+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T13:23:01.919+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:23:01.919+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:23:01.951+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:23:01.951+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T13:23:01.952+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:23:01.952+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T13:23:01.952+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:23:01.975+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2024-03-08T13:33:53.899+0530] {processor.py:161} INFO - Started process (PID=15464) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:33:53.900+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T13:33:53.901+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:33:53.901+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:33:53.933+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:33:53.933+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T13:33:53.933+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:33:53.933+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T13:33:53.933+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:33:53.957+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T13:35:45.619+0530] {processor.py:161} INFO - Started process (PID=15551) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:35:45.620+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T13:35:45.620+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:35:45.620+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:35:45.653+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:35:45.653+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T13:35:45.653+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:35:45.653+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T13:35:45.653+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:35:45.677+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T13:37:38.447+0530] {processor.py:161} INFO - Started process (PID=15625) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:37:38.448+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T13:37:38.448+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:37:38.448+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:37:38.481+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:37:38.480+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T13:37:38.481+0530] {logging_mixin.py:188} INFO - [2024-03-08T13:37:38.481+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T13:37:38.481+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T13:37:38.505+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T14:24:18.663+0530] {processor.py:161} INFO - Started process (PID=16699) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:24:18.664+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T14:24:18.665+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:24:18.664+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:24:18.698+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:24:18.698+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T14:24:18.699+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:24:18.698+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T14:24:18.699+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:24:18.723+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2024-03-08T14:28:37.841+0530] {processor.py:161} INFO - Started process (PID=16986) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:28:37.841+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T14:28:37.841+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:28:37.841+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:28:37.876+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:28:37.876+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T14:28:37.876+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:28:37.876+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T14:28:37.876+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:28:37.901+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2024-03-08T14:30:25.357+0530] {processor.py:161} INFO - Started process (PID=17060) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:30:25.357+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T14:30:25.357+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:30:25.357+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:30:25.391+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:30:25.391+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T14:30:25.391+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:30:25.391+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T14:30:25.392+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:30:25.415+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2024-03-08T14:34:07.025+0530] {processor.py:161} INFO - Started process (PID=17307) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:34:07.026+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T14:34:07.026+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:34:07.026+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:34:07.059+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:34:07.058+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T14:34:07.059+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:34:07.059+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T14:34:07.059+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:34:07.082+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T14:35:59.091+0530] {processor.py:161} INFO - Started process (PID=17390) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:35:59.092+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T14:35:59.092+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:35:59.092+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:35:59.126+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:35:59.126+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T14:35:59.126+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:35:59.126+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T14:35:59.126+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:35:59.149+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2024-03-08T14:37:49.932+0530] {processor.py:161} INFO - Started process (PID=17461) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:37:49.933+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T14:37:49.933+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:37:49.933+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:37:49.965+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:37:49.965+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T14:37:49.965+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:37:49.965+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T14:37:49.965+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:37:49.988+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2024-03-08T14:39:32.961+0530] {processor.py:161} INFO - Started process (PID=17529) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:39:32.962+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T14:39:32.962+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:39:32.962+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:39:32.993+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:39:32.993+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T14:39:32.994+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:39:32.993+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T14:39:32.994+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:39:33.017+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2024-03-08T14:41:19.501+0530] {processor.py:161} INFO - Started process (PID=17598) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:41:19.502+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T14:41:19.502+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:41:19.502+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:41:19.534+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:41:19.534+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T14:41:19.535+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:41:19.535+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T14:41:19.535+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:41:19.558+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T14:43:05.149+0530] {processor.py:161} INFO - Started process (PID=17666) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:43:05.149+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T14:43:05.149+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:43:05.149+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:43:05.181+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:43:05.181+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T14:43:05.181+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:43:05.181+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T14:43:05.181+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:43:05.204+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2024-03-08T14:53:16.726+0530] {processor.py:161} INFO - Started process (PID=18005) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:53:16.726+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T14:53:16.727+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:53:16.726+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:53:16.759+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:53:16.759+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T14:53:16.759+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:53:16.759+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T14:53:16.759+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:53:16.783+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2024-03-08T14:55:05.093+0530] {processor.py:161} INFO - Started process (PID=18179) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:55:05.094+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T14:55:05.094+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:55:05.094+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:55:05.127+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:55:05.127+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T14:55:05.127+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:55:05.127+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T14:55:05.127+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:55:05.151+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T14:56:47.886+0530] {processor.py:161} INFO - Started process (PID=18247) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:56:47.887+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T14:56:47.887+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:56:47.887+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:56:47.919+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:56:47.919+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T14:56:47.919+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:56:47.919+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T14:56:47.919+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:56:47.943+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2024-03-08T14:58:40.008+0530] {processor.py:161} INFO - Started process (PID=18318) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:58:40.009+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T14:58:40.009+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:58:40.009+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:58:40.042+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:58:40.042+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T14:58:40.042+0530] {logging_mixin.py:188} INFO - [2024-03-08T14:58:40.042+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T14:58:40.042+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T14:58:40.066+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T15:00:37.379+0530] {processor.py:161} INFO - Started process (PID=18392) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T15:00:37.380+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T15:00:37.380+0530] {logging_mixin.py:188} INFO - [2024-03-08T15:00:37.380+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T15:00:37.412+0530] {logging_mixin.py:188} INFO - [2024-03-08T15:00:37.412+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T15:00:37.413+0530] {logging_mixin.py:188} INFO - [2024-03-08T15:00:37.412+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T15:00:37.413+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T15:00:37.436+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T15:02:32.807+0530] {processor.py:161} INFO - Started process (PID=18469) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T15:02:32.808+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T15:02:32.808+0530] {logging_mixin.py:188} INFO - [2024-03-08T15:02:32.808+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T15:02:32.840+0530] {logging_mixin.py:188} INFO - [2024-03-08T15:02:32.840+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T15:02:32.840+0530] {logging_mixin.py:188} INFO - [2024-03-08T15:02:32.840+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T15:02:32.840+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T15:02:32.863+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2024-03-08T15:04:15.492+0530] {processor.py:161} INFO - Started process (PID=18539) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T15:04:15.493+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T15:04:15.493+0530] {logging_mixin.py:188} INFO - [2024-03-08T15:04:15.493+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T15:04:15.526+0530] {logging_mixin.py:188} INFO - [2024-03-08T15:04:15.526+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T15:04:15.526+0530] {logging_mixin.py:188} INFO - [2024-03-08T15:04:15.526+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T15:04:15.526+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T15:04:15.551+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2024-03-08T15:06:06.248+0530] {processor.py:161} INFO - Started process (PID=18610) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T15:06:06.249+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T15:06:06.249+0530] {logging_mixin.py:188} INFO - [2024-03-08T15:06:06.249+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T15:06:06.282+0530] {logging_mixin.py:188} INFO - [2024-03-08T15:06:06.282+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T15:06:06.282+0530] {logging_mixin.py:188} INFO - [2024-03-08T15:06:06.282+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T15:06:06.282+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T15:06:06.306+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-08T16:49:32.248+0530] {processor.py:161} INFO - Started process (PID=1256) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T16:49:32.249+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T16:49:32.249+0530] {logging_mixin.py:188} INFO - [2024-03-08T16:49:32.249+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T16:49:32.281+0530] {logging_mixin.py:188} INFO - [2024-03-08T16:49:32.281+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T16:49:32.281+0530] {logging_mixin.py:188} INFO - [2024-03-08T16:49:32.281+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T16:49:32.281+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T16:49:32.305+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2024-03-08T16:53:51.938+0530] {processor.py:161} INFO - Started process (PID=1572) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T16:53:51.938+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T16:53:51.939+0530] {logging_mixin.py:188} INFO - [2024-03-08T16:53:51.939+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T16:53:51.972+0530] {logging_mixin.py:188} INFO - [2024-03-08T16:53:51.972+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T16:53:51.972+0530] {logging_mixin.py:188} INFO - [2024-03-08T16:53:51.972+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T16:53:51.972+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T16:53:51.997+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2024-03-08T16:55:49.403+0530] {processor.py:161} INFO - Started process (PID=1657) to work on /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T16:55:49.404+0530] {processor.py:830} INFO - Processing file /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-08T16:55:49.404+0530] {logging_mixin.py:188} INFO - [2024-03-08T16:55:49.404+0530] {dagbag.py:540} INFO - Filling up the DagBag from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T16:55:49.437+0530] {logging_mixin.py:188} INFO - [2024-03-08T16:55:49.436+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-08T16:55:49.437+0530] {logging_mixin.py:188} INFO - [2024-03-08T16:55:49.437+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-08T16:55:49.437+0530] {processor.py:842} WARNING - No viable dags retrieved from /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-08T16:55:49.460+0530] {processor.py:183} INFO - Processing /Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
