[2024-03-08T14:12:42.265+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.compute_averages scheduled__2024-03-07T00:33:00+00:00 [queued]>
[2024-03-08T14:12:42.267+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.compute_averages scheduled__2024-03-07T00:33:00+00:00 [queued]>
[2024-03-08T14:12:42.267+0530] {taskinstance.py:2193} INFO - Starting attempt 7 of 8
[2024-03-08T14:12:42.271+0530] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): compute_averages> on 2024-03-07 00:33:00+00:00
[2024-03-08T14:12:42.275+0530] {standard_task_runner.py:60} INFO - Started process 16022 to run task
[2024-03-08T14:12:42.278+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_pipeline', 'compute_averages', 'scheduled__2024-03-07T00:33:00+00:00', '--job-id', '647', '--raw', '--subdir', 'DAGS_FOLDER/Data_analysis.py', '--cfg-path', '/var/folders/th/tnjyp6yd1cj78nysn5t4jl6h0000gn/T/tmptkj1ayww']
[2024-03-08T14:12:42.278+0530] {standard_task_runner.py:88} INFO - Job 647: Subtask compute_averages
[2024-03-08T14:18:59.298+0530] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-03-08T14:18:59.301+0530] {process_utils.py:131} INFO - Sending 15 to group 16022. PIDs of all processes in the group: [16022]
[2024-03-08T14:18:59.301+0530] {process_utils.py:86} INFO - Sending the signal 15 to group 16022
[2024-03-08T14:18:59.305+0530] {process_utils.py:79} INFO - Process psutil.Process(pid=16022, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='14:12:42') (16022) terminated with exit code -15
